### ISSUE TITLE
AbbyyOnlineSdk.py header error

### ISSUE THREAD

**Issue by kungfujam** [abbyysdk/ocrsdk.com#27]
In order to get this to work (to stop a newline being added to the header making it invalid), had to change line 90:
from:
> return { "Authorization" : "Basic %s" % base64.encodestring( "%s:%s" % (self.ApplicationId, self.Password) ) } 

to:
> return { "Authorization" : "Basic %s" % base64.b64encode( "%s:%s" % (self.ApplicationId, self.Password) ) }

System details:
Mac 10.10.4 
Python 2.7.10 |Anaconda 2.3.0 (x86_64)| (default, May 28 2015, 17:04:42) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin

Error message:
Traceback (most recent call last):
  File "process.py", line 94, in <module>
    recognizeFile( sourceFile, targetFile, language, outputFormat )	
  File "process.py", line 40, in recognizeFile
    task = processor.ProcessImage( filePath, settings )
  File "/Users/kungfujam/git/ocrsdk.com/Python/AbbyyOnlineSdk.py", line 52, in ProcessImage
    response = self.getOpener().open(request, bodyParams).read()
  File "/Users/kungfujam/anaconda/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/Users/kungfujam/anaconda/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/Users/kungfujam/anaconda/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/Users/kungfujam/anaconda/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/Users/kungfujam/anaconda/lib/python2.7/urllib2.py", line 1194, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/Users/kungfujam/anaconda/lib/python2.7/httplib.py", line 1053, in request
    self._send_request(method, url, body, headers)
  File "/Users/kungfujam/anaconda/lib/python2.7/httplib.py", line 1092, in _send_request
    self.putheader(hdr, value)
  File "/Users/kungfujam/anaconda/lib/python2.7/httplib.py", line 1031, in putheader
    raise ValueError('Invalid header value %r' % (one_value,))
ValueError: Invalid header value 'Basic dXNlcjpwYXNzd29yZA==\n'

**Comment by Dmitry-Me** [comment]
Applied with https://github.com/abbyysdk/ocrsdk.com/commit/6d86c6e7ba86e6af4d5c52bb7eeca27cf78fde7e Thanks a lot for reporting this. Do you have any idea why we were able to run this very code and get no error messages?

**Comment by kungfujam** [comment]
Sorry, I haven't a clue! I guess there have been some changes to the behaviour of base64.encodestring. I got my solution from here: https://fedorahosted.org/suds/ticket/427
