### ISSUE TITLE
processing a image file filed 

### ISSUE THREAD

**Issue by TuxRaju** [abbyysdk/ocrsdk.com#42]
python .\Python\process.py AFS COI-page-001.jpg myfil
e -rtf
Traceback (most recent call last):
  File ".\Python\process.py", line 8, in <module>
    import MultipartPostHandler
  File "C:\\Python\MultipartPostHandler.py", line 73
    raise TypeError, "not a valid non-string sequence or mapping object", traceb
ack
                   ^
SyntaxError: invalid syntax

**Comment by Dmitry-Me** [comment]
The original code is here https://github.com/abbyysdk/ocrsdk.com/blob/master/Python/MultipartPostHandler.py#L73 and there the word `traceback` in fully on one line. The error message you have says the word somehow got split into two words `traceb` and `ack`.
